c = {}
c.PL_ACT= "pl_act"
c.DIALOGUE = "dialogue"
c.STACK_MENU = "stack_menu"
c.PLAYER_MENU= "player_menu"
c.PL_MOVE = "pl_move"
c.PL_IDLE = "pl_idle"
c.PL_CARRY_IDLE="pl_carry_idle"
c.PL_CARRY_MOVE="pl_carry_move"
c.BUTTON_ONE="v"
c.BUTTON_TWO="b"
c.OPENING="opening"
c.OPEN="open"
c.CLOSING="closing"
c.CLOSED="closed"
c.w=16
c.h=16
c.DIR_UP=4
c.DIR_DOWN=3
c.DIR_LEFT=2
c.DIR_RIGHT=1
return c