c = {}
c.PL_ACT= "pl_act"
c.DIALOGUE = "dialogue"
c.STACK_MENU = "stack_menu"
c.PLAYER_MENU= "player_menu"
c.PL_MOVE = "pl_move"
c.PL_IDLE = "pl_idle"
c.IN="in"
c.OUT="out"
c.PL_CARRY_IDLE="pl_carry_idle"
c.PL_CARRY_MOVE="pl_carry_move"
c.RECORD_STACK="record_stack"
c.RECORD_PLAYER="record_player"
c.ROOM_TRANSITION="room_transition"
c.TITLE_MENU="title_menu"
c.BUTTON_ONE="space"
c.BUTTON_TWO="escape"
c.OPENING="opening"
c.OPEN="open"
c.CLOSING="closing"
c.CLOSED="closed"
c.DOOR="door"
c.ROOM="room"
c.ROOM_1 = "room_1"
c.ROOM_2 = "room_2"
c.ROOM_3 = "room_3"
c.ROOM_4 = "room_4"
c.w=16
c.h=16
c.DIR_UP=4
c.DIR_DOWN=3
c.DIR_LEFT=2
c.DIR_RIGHT=1
return c